### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by BigDeepBlue** [inikishin/ugc_sprint_2#1]
Здравствуйте Илья. Хорошо потрудились, работа обширная, сделано много. Далее замечания:

1. Хотелось бы более развернутую документацию в [README](https://github.com/inikishin/ugc_sprint_2/blob/main/README.md) касающуюся текущего ugc_service спринта, например:
- сейчас описание структуры проекта заканчивается примерно на auth_service спринте, и ничего не сказано по поводу UGC сервисов, ни о назначении ugc_api ни о ugc_etl, хотя код присутствует (но ссылка на swagger была бы кстати).
- при реализации функционала хранения закладок вы выбрали kafka как хранилище, интересно почему вы выбрали это решение, хотелось бы видеть результаты исследований  на эту тему, почему пришли именно к такому решению.
- вы построили систему сборов логов, провели хорошую работу, также неплохо было добавить раздел с описанием как этой штукой пользоваться. Можно даже присоединить скриншоты, ссылку на kibana.

2. [Здесь](https://github.com/inikishin/ugc_sprint_2/blob/main/requirements.txt) вы собрали все зависимости, которые используются в разных микросервисах. Это приводит к тому что в образ с ugc_api устанавливается Flask и другие зависимости которые в принципе для работы сервиса не нужны. Хорошая практика иметь у каждого микросервиса свой отдельный requirements.txt c перечнем пакетов необходимых для работы именно этого конкретного сервиса. Так Ваши образы станут меньше, собираться быстрее, к тому же сейчас изменение requirements.txt приведет к пересборке всех образов. Это нужно починить.
3.  Вы выбрали асинхронный фреймворк fastapi для реализации ugc_api , следовательно нужно аккуратно подходить к выбору используемых библиотек, нужно выбирать их асинхронные версии, которые устроены так, что не выполняют блокирующие запросы.

-  [здесь](https://github.com/inikishin/ugc_sprint_2/blob/9fedada8f9a0f07d47fbf19e9c8a48e35e8222a5/ugc_api/src/api/v1/events.py#L41)  вы определили как async, но внутри на самом деле не происходит никакого async. Метод [сервиса](https://github.com/inikishin/ugc_sprint_2/blob/9fedada8f9a0f07d47fbf19e9c8a48e35e8222a5/ugc_api/src/services/event_service.py#L27) использует синхронную версию библиотеки для работы с kafka. Это приводит к тому, что все вызовы к kafka  
будут блокирующие и это наверное совсем не то что вы ожидаете.
Чтоб починить, посмотрите [aiokafka](https://aiokafka.readthedocs.io/en/stable/index.html) библиотеку и ее [AIOKafkaProducer](https://aiokafka.readthedocs.io/en/stable/index.html#aiokafkaproducer)

-  тоже касается использования библиотеки [requests](https://github.com/inikishin/ugc_sprint_2/blob/9fedada8f9a0f07d47fbf19e9c8a48e35e8222a5/ugc_api/src/middleware/auth_middleware.py#L19) этот вызов блокирующий и у вас будет все замирать ожидая ответа от сервиса авторизации. Для этих целей можно посмотреть библиотеку [httpx](https://www.python-httpx.org/) либо [aiohttp](https://docs.aiohttp.org/en/stable/client.html). Ну или другую на Ваш выбор, но она не должна быть блокирующей.

4. [Модельки](https://github.com/inikishin/ugc_sprint_2/blob/9fedada8f9a0f07d47fbf19e9c8a48e35e8222a5/ugc_api/src/api/v1/events.py#L9)
лучше вынести в отдельный модуль.

5. [Так](https://github.com/inikishin/ugc_sprint_2/blob/9fedada8f9a0f07d47fbf19e9c8a48e35e8222a5/ugc_api/src/api/v1/events.py#L37) возвращать просто "ок" можно, но лучше написать модельку [ответа](https://fastapi.tiangolo.com/tutorial/response-model/#response-model) например
```
from fastapi import status

class SuccessResponse(BaseModel):
    status: bool = True
# а ваш route

@router.post('/send_bookmark/', summary='Добавить фильма в закладки', 
                      response_model=SuccessResponse, status_code=status.HTTP_201_CREATED)
async def send_bookmark(movie_bookmark: MovieBookmark,
....
    return {"status": True}
``` 

6. Пустой [файлик](https://github.com/inikishin/ugc_sprint_2/blob/main/ugc_api/src/logging.conf) не нужно хранить в репозитории.
7. [Здесь](https://github.com/inikishin/ugc_sprint_2/blob/9fedada8f9a0f07d47fbf19e9c8a48e35e8222a5/ugc_api/.env.example#L2) в примере настроек нужно пересмотреть сервис и записать все переменные которые можно конфигурировать. Например не хватает настроек [sentry](https://github.com/inikishin/ugc_sprint_2/blob/9fedada8f9a0f07d47fbf19e9c8a48e35e8222a5/ugc_api/src/main.py#L20).
8. Зачем здесь устанавливается [curl](https://github.com/inikishin/ugc_sprint_2/blob/9fedada8f9a0f07d47fbf19e9c8a48e35e8222a5/ugc_api/Dockerfile#L6) ? Если он не нужен, лучше убрать.
9. [Здесь](https://github.com/inikishin/ugc_sprint_2/blob/9fedada8f9a0f07d47fbf19e9c8a48e35e8222a5/.deploy/filebeat.yml#L1) лучше  использовать новый синтаксис конфигурации [filebeat](https://www.elastic.co/guide/en/beats/filebeat/8.4/filebeat-input-log.html#filebeat-input-log), потому что Вы используете [8.4.1](https://github.com/inikishin/ugc_sprint_2/blob/main/docker-compose.yml#L220) версию, а синтаксис 7.х deprecated.
Вам нужно попытаться сконфигурировать так (добавить теги), чтоб в elk-elastic Вы смогли писать в разные индексы от разных сервисов.
10. [Здесь](https://github.com/inikishin/ugc_sprint_2/blob/9fedada8f9a0f07d47fbf19e9c8a48e35e8222a5/.deploy/logstash.conf#L15) у вас пишется все в один индекс  но у вас уже множество сервисов (выдачи контента, авторизации, ugc, админка и т.д.) , Попробуйте разделить, например так:
```
      ...
        if ( [tag] == "nginx" ) {
            elasticsearch {
              hosts => [ "${ES_HOST}" ]
              index => "nginx-%{+YYYY.MM.dd}"
            }
        }
        else if ( [tag] == "auth_app" ) {
            elasticsearch {
              hosts => [ "${ES_HOST}" ]
              index => "auth_app-%{+YYYY.MM.dd}"
            }
        }
        else if ( [tag] == "ugc_api" ) {
            elasticsearch {
              hosts => [ "${ES_HOST}" ]
              index => "ugc_api-%{+YYYY.MM.dd}"
            }
        }
      ...
```
и в самом сервисе ugc_api подкрутить логирование чтоб все сыпалось в elk  (примерный набросок, но ключевое, как добавить tag)
```
      @app.middleware('http')
      async def loggin(request: Request, call_next):
          response = await call_next(request)
          request_id = request.headers.get('X-Request-Id')
          custom_logger = logging.LoggerAdapter(
              logger, extra={'tag': 'ugc_api', 'request_id': request_id}
          )
          custom_logger.info(request)
          return response
```

**Comment by inikishin** [comment]
Замечания поправлены
